spring:
  datasource:
    url: jdbc:oracle:thin:@DB202203091416_high?TNS_ADMIN=./common/Wallet_DB202203091416
    username: admin
    password: Cloudoracle123
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: create-drop
      format-sql: true

server:
  port: 8088
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: info
    org.springframework: DEBUG


