spring:
  servlet:
    multipart:
      max-file-size: 1024KB
      max-request-size: 1024KB
  datasource:
    url: jdbc:oracle:thin:@DB202203091416_high?TNS_ADMIN=./common/Wallet_DB202203091416
    username: admin
    password: Cloudoracle123
    driver-class-name: oracle.jdbc.OracleDriver
    initialization-mode: never


  jpa:
    defer-datasource-initialization: true
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: none
      format-sql: true

  thymeleaf:
    cache: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8088
  error:
    include-message: always
    include-binding-errors: always


logging:
  level:
    root: info
    org.springframework: DEBUG


