spring:
  datasource:
    url: jdbc:oracle:thin:@DB202203091416_high?TNS_ADMIN=./common/Wallet_DB202203091416
    username: admin
    password: Cloudoracle123
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    properties:
      hibernate:
        ddl-auto: create-drop
        show_sql: true
        format_sql: true
logging:
  level:
    org.springframework: DEBUG
server:
  port: 8088


